#pragma once
#include QMK_KEYBOARD_H

/* base alpha keys and right side special chars */

#define MADROW12345  KC_1, KC_2, KC_3, KC_4, KC_5
#define MADROWQWERT  KC_Q, KC_W, KC_E, KC_R, KC_T
#define MADROWASDFG  KC_A, KC_S, KC_D, KC_F, KC_G
#define MADROWZXCVB  KC_Z, KC_X, KC_C, KC_V, KC_B

#define MADROW67890  KC_6, KC_7, KC_8, KC_9, KC_0
#define MADROWYUIOP  KC_Y, KC_U, KC_I, KC_O, KC_P
#define MADROWHJKL   KC_H, KC_J, KC_K, KC_L
#define MADROWNM     KC_N, KC_M

#define MADROWSEMICOL KC_SCLN
#define MADROWCOMDOT  KC_COMM,  KC_DOT

#define MADROWNUM     MADROW12345, MADROW67890
#define MADROWQ       MADROWQWERT, MADROWYUIOP
#define MADROWA       MADROWASDFG, MADROWHJKL, MADROWSEMICOL
#define MADROWZ       MADROWZXCVB, MADROWNM, MADROWCOMDOT

/* lower alphas */

#define MADROW12345LOW  KC_EXLM, KC_AT,   KC_HASH, KC_DLR,  KC_PERC
#define MADROWQWERTLOW  KC_EXLM, KC_AT,   KC_HASH, KC_DLR,  KC_PERC
#define MADROWASDFGLOW  KC_F1,   KC_F2,   KC_F3,   KC_F4,   KC_F5
#define MADROWZXCVBLOW  KC_F7,   KC_F8,   KC_F9,   KC_F10,  KC_F11

#define MADROW67890LOW  KC_CIRC, KC_AMPR, KC_ASTR, KC_LPRN, KC_RPRN
#define MADROWYUIOPLOW  KC_CIRC, KC_AMPR, KC_ASTR, KC_LCBR, KC_RCBR
#define MADROWHJKLLOW   KC_F6,   KC_UNDS, KC_PLUS, KC_LBRC
#define MADROWNMLOW     KC_F12,S(KC_NUHS)

#define MADROWSEMICOLLOW  KC_RBRC
#define MADROWCOMDOTLOW   S(KC_NUBS),KC_HOME

#define MADROWNUMLOW     MADROW12345LOW, MADROW67890LOW
#define MADROWQLOW       MADROWQWERTLOW, MADROWYUIOPLOW
#define MADROWALOW       MADROWASDFGLOW, MADROWHJKLLOW, MADROWSEMICOLLOW
#define MADROWZLOW       MADROWZXCVBLOW, MADROWNMLOW, MADROWCOMDOTLOW

/* raise alphas */

#define MADROW12345RAI  KC_1,    KC_2,    KC_3,    KC_4,    KC_5
#define MADROWQWERTRAI  KC_1,    KC_2,    KC_3,    KC_4,    KC_5
#define MADROWASDFGRAI  KC_F1,   KC_F2,   KC_F3,   KC_F4,   KC_F5
#define MADROWZXCVBRAI  KC_F7,   KC_F8,   KC_F9,   KC_F10,  KC_F11

#define MADROW67890RAI  KC_6,    KC_7,    KC_8,    KC_9,    KC_0
#define MADROWYUIOPRAI  KC_6,    KC_7,    KC_8,    KC_9,    KC_0
#define MADROWHJKLRAI   KC_F6,   KC_MINS, KC_EQL,  KC_LBRC
#define MADROWNMRAI     KC_F12,  KC_NUHS

#define MADROWSEMICOLRAI  KC_RBRC
#define MADROWCOMDOTRAI   KC_NUBS, KC_PGUP

#define MADROWNUMRAI     MADROW12345RAI, MADROW67890RAI
#define MADROWQRAI       MADROWQWERTRAI, MADROWYUIOPRAI
#define MADROWARAI       MADROWASDFGRAI, MADROWHJKLRAI, MADROWSEMICOLRAI
#define MADROWZRAI       MADROWZXCVBRAI, MADROWNMRAI, MADROWCOMDOTRAI
